### PR TITLE
CHG rename professor column in Course to professor_display_name

### PR DESCRIPTION
**Pull request by AlpacaMax**
This PR is the result of discussion in #164. I changed every place I can think of that accesses this column or field. Please take a look and see if I missed something.

### CODE REVIEW

**Comment by AlpacaMax** [comment]
I see what's wrong here. I'll fix it real quick.

**Comment by AlpacaMax** [comment]
Although the checks are passed, I'm not sure if I broke the frontend code of creating new courses. And I can't quite test it cuz when I run Anubis in debug mode locally the frontend code runs on a different port yet tries to access the api through its own port. Not sure if I'm doing it right though.

**Comment by wabscale** [comment]
Awesome work. It appears that you got everything I had in mind for this. I'll test this out tomorrow and get it merged.

Great stuff Max :+1:

**Comment by wabscale** [comment]
Sorry for the delay Max. Everything looks good. Merging now. Thanks for the great work!

**Comment by AlpacaMax** [comment]
Yeah no problem

**Pull request merged**
