### PR TITLE
Fix whoami bug

### PR DESCRIPTION
**Pull request by AlpacaMax**
This PR fixes the `whoami` bug mentioned in #115 . Now when we access `/api/public/auth/whoami`, specifically when we access `User.data` property:
- The `professor_for` field lists the  courses the user is a professor for
- The `ta_for` field lists the courses the user is either a professor or a ta for
- The `admin_for` field is the union of `ta_for` and `professor_for`

Some of the issues that happened or discovered when I was coding this new logic:
- The original plan mentioned by @wabscale in #115 , which is to add this logic under `api/anubis/utils/lms/courses.py`, does not work because it will introduce cyclic association and I don't think it fits into any other places. So I just add it as a property under the `User` model.
- I attempted to separate each model into its own file but failed due to cyclic association. This attempt alongside with the reason behind it are mentioned in #115 . Still I vaguely remember that there's a way to work around this problem in flask without introducing too many codes. Further attempts can be made in the future.
- This new logic actually makes `admin_for` redundant as it will always be the same as `ta_for`. Efforts need to be made to remove this field and change all the frontend code that access this field.

### CODE REVIEW

**Comment by wabscale** [comment]
Great stuff Max. Just a couple small things, and we'll get this merged.

I definitely see your point about keeping logic to specific things together. In early versions of Anubis, I used methods on sqlalchemy models all over the place. This was back when there were only like 5 or 6 tables. The file blew up in size. It was something like 3000 lines at one point. If we start to add methods and functions to the models, we're going to end up putting all the logic in anubis in that one file. At one point it was pretty much that way, and I really want to avoid that (especially since the system is so so much larger now).

With the cyclic imports, we get around this by doing the import in the function. With the way python does imports, this is just necessary sometimes. The function will actually only be imported the first time. Every other time it reads the module out of an internal cache `sys.modules` (this is getting too much into the internals of python lol). In the User.data property it would be something like this:

```python
class User(db.Model):
    # ...
    @property
    def data(self):
        from anubis.utils.lms.courses import get_user_permissions
        return {
            # ...
            **get_user_permissions(self)
        }
```

So if you could move that `get_user_permissions` property to the utils/lms/courses.py, we should be good to go. Thanks for the great work.

**Comment by AlpacaMax** [comment]
Hey I've never heard of that workaround method! I'll do it.

BTW, do you think it's a good idea to separate models into different files? With this workaround method it might actually work!

**Comment by wabscale** [comment]
Yeah I have thought about moving them into different files, and tried it once. You can do it with sqlalchemy, but it can be a bit annoying. You have do do foreign keys in strings, not as object references. It's not the biggest deal in the world, but IMO i think it is a bit of an unnecessary rewrite.

As long as we keep that file focused, then I think we are good.

**Review by wabscale — APPROVED** [review]

**Comment by wabscale** [comment]
Everything looks good. Tests are passing. Merging now.

**Pull request merged**
